<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS8618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ishqnama.Domain\Ishqnama.Domain.csproj" />
    <ProjectReference Include="..\Ishqnama.Application\Ishqnama.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
  </ItemGroup>
</Project>
