/**
 * Reader-facing words for verse lists. Same rules as the readiness and sign-in copy: no
 * "service", "API", "server", "account", "log in" or "session"; readers are often unfamiliar
 * with technology. `src/config/__tests__/lists-copy.test.ts` checks every string here.
 */
export const LISTS_COPY = {
  tab: "Lists",
  myCollection: "My collection",
  featured: "Featured",
  savedLists: "Saved",
  newList: "New list",
  draft: "Draft",
  published: "Published",
  edit: "Edit",
  emptyTitle: "No lists yet",
  emptyBody: "Gather ayaat into a list, then share it with others.",
  noLongerAvailable: "No longer available",
  remove: "Remove",
  compiledBy: "Compiled by",
  aReader: "A reader",
  admin: "Admin",
  openInReader: "Open in reader",
  readMore: "Read more",
  share: "Share",
  favourite: "Add to favourites",
  favourited: "In your favourites",
  favouriteFailed: "Couldn't add it to your favourites. Try again.",
  notAvailableTitle: "This list isn't available",
  notAvailableBody: "It may have been taken down, or the link is incomplete.",
  loading: "Opening the list",
  listsWarming: "Your lists will appear shortly",
  listsUnreachable: "Couldn't load your lists yet",
  copiedLink: "Link copied. Paste it wherever you like.",
  shareFailed: "Couldn't share from here. Try again.",
  // Editor
  editorHeading: "Edit list",
  titleLabel: "Title",
  titlePlaceholder: 'For example: "Verses to memorise"',
  descriptionLabel: "Description",
  descriptionPlaceholder: "What gathers these ayaat together",
  groupsHeading: "Groups of ayaat",
  addGroup: "Add group",
  chapterLabel: "Sura",
  fromLabel: "From ayah",
  toLabel: "To ayah",
  captionLabel: "Caption",
  captionPlaceholder: "Optional note for these verses",
  moveUp: "Move up",
  moveDown: "Move down",
  removeGroup: "Remove group",
  noGroups: "Add a group of ayaat to begin.",
  groupInvalid: "Choose ayaat of this sura, from 1 to",
  saving: "Saving",
  saved: "Saved",
  saveFailed: "Not saved yet. Saving again once the site is reachable.",
  publish: "Publish",
  unpublish: "Unpublish",
  publishTitle: "Publish this list?",
  publishMessage: "Your name will show on it, and anyone with the link can read it.",
  unpublishTitle: "Unpublish this list?",
  unpublishMessage: "The link will stop working until you publish it again.",
  deleteList: "Delete list",
  deleteTitle: "Delete this list?",
  deleteMessage: "It will be gone for good, along with its link.",
  view: "View",
  // Create dialog
  create: "Create",
  creating: "Creating",
  createFailed: "Couldn't create the list. Please try again.",
  createTimeout: "Couldn't create the list yet. Please try again.",
  // Add to list from the reader
  addToList: "Add to list",
  addToListHeading: "Add to a list",
  chooseList: "Choose a list",
  adding: "Adding",
  addedTo: "Added to",
  addFailed: "Couldn't add it yet. Please try again.",
  listFull: "This list is full.",
} as const;

export type ListsCopyKey = keyof typeof LISTS_COPY;
